// <auto-generated />
using System;
using CvBlog.Data.Concrete.EntityFramework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CvBlog.Data.Migrations
{
    [DbContext(typeof(CvBlogAppContext))]
    [Migration("20241224080127_SeedingCategories")]
    partial class SeedingCategories
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CvBlog.Entities.Concrete.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CommentCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SeoAuthor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SeoDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeoTags")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Articles", (string)null);
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7189),
                            Description = "Açıklama1",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7190),
                            Name = "Kategori1",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 2,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7209),
                            Description = "Açıklama2",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7210),
                            Name = "Kategori2",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 3,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7213),
                            Description = "Açıklama3",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7214),
                            Name = "Kategori3",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 4,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7217),
                            Description = "Açıklama4",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7218),
                            Name = "Kategori4",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 5,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7221),
                            Description = "Açıklama5",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7221),
                            Name = "Kategori5",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 6,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7226),
                            Description = "Açıklama6",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7227),
                            Name = "Kategori6",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 7,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7230),
                            Description = "Açıklama7",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7231),
                            Name = "Kategori7",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 8,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7233),
                            Description = "Açıklama8",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7234),
                            Name = "Kategori8",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 9,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7237),
                            Description = "Açıklama9",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7237),
                            Name = "Kategori9",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 10,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7242),
                            Description = "Açıklama10",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7242),
                            Name = "Kategori10",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 11,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7245),
                            Description = "Açıklama11",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7246),
                            Name = "Kategori11",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 12,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7249),
                            Description = "Açıklama12",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7249),
                            Name = "Kategori12",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 13,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7252),
                            Description = "Açıklama13",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7253),
                            Name = "Kategori13",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 14,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7256),
                            Description = "Açıklama14",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7256),
                            Name = "Kategori14",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 15,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7259),
                            Description = "Açıklama15",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7260),
                            Name = "Kategori15",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 16,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7263),
                            Description = "Açıklama16",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7263),
                            Name = "Kategori16",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 17,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7299),
                            Description = "Açıklama17",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7300),
                            Name = "Kategori17",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 18,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7304),
                            Description = "Açıklama18",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7305),
                            Name = "Kategori18",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 19,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7308),
                            Description = "Açıklama19",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7308),
                            Name = "Kategori19",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 20,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7311),
                            Description = "Açıklama20",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7312),
                            Name = "Kategori20",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 21,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7315),
                            Description = "Açıklama21",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7315),
                            Name = "Kategori21",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 22,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7318),
                            Description = "Açıklama22",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7319),
                            Name = "Kategori22",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 23,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7322),
                            Description = "Açıklama23",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7322),
                            Name = "Kategori23",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 24,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7325),
                            Description = "Açıklama24",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7326),
                            Name = "Kategori24",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 25,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7329),
                            Description = "Açıklama25",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7329),
                            Name = "Kategori25",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 26,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7332),
                            Description = "Açıklama26",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7332),
                            Name = "Kategori26",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 27,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7335),
                            Description = "Açıklama27",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7336),
                            Name = "Kategori27",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 28,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7339),
                            Description = "Açıklama28",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7339),
                            Name = "Kategori28",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 29,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7342),
                            Description = "Açıklama29",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7343),
                            Name = "Kategori29",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 30,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7346),
                            Description = "Açıklama30",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7346),
                            Name = "Kategori30",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 31,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7349),
                            Description = "Açıklama31",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7350),
                            Name = "Kategori31",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 32,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7353),
                            Description = "Açıklama32",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7353),
                            Name = "Kategori32",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 33,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7356),
                            Description = "Açıklama33",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7357),
                            Name = "Kategori33",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 34,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7360),
                            Description = "Açıklama34",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7361),
                            Name = "Kategori34",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 35,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7364),
                            Description = "Açıklama35",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7364),
                            Name = "Kategori35",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 36,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7367),
                            Description = "Açıklama36",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7368),
                            Name = "Kategori36",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 37,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7378),
                            Description = "Açıklama37",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7379),
                            Name = "Kategori37",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 38,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7382),
                            Description = "Açıklama38",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7382),
                            Name = "Kategori38",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 39,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7385),
                            Description = "Açıklama39",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7386),
                            Name = "Kategori39",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 40,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7389),
                            Description = "Açıklama40",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7389),
                            Name = "Kategori40",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 41,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7392),
                            Description = "Açıklama41",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7393),
                            Name = "Kategori41",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 42,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7396),
                            Description = "Açıklama42",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7396),
                            Name = "Kategori42",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 43,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7399),
                            Description = "Açıklama43",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7400),
                            Name = "Kategori43",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 44,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7403),
                            Description = "Açıklama44",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7403),
                            Name = "Kategori44",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 45,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7406),
                            Description = "Açıklama45",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7406),
                            Name = "Kategori45",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 46,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7410),
                            Description = "Açıklama46",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7410),
                            Name = "Kategori46",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 47,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7413),
                            Description = "Açıklama47",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7414),
                            Name = "Kategori47",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 48,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7418),
                            Description = "Açıklama48",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7418),
                            Name = "Kategori48",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 49,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7421),
                            Description = "Açıklama49",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7422),
                            Name = "Kategori49",
                            Note = "CategoryMap'ten kaydedildi."
                        },
                        new
                        {
                            Id = 50,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7425),
                            Description = "Açıklama50",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 67, DateTimeKind.Local).AddTicks(7425),
                            Name = "Kategori50",
                            Note = "CategoryMap'ten kaydedildi."
                        });
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.CompetencyLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("CompetencyLevels", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 68, DateTimeKind.Local).AddTicks(1785),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 68, DateTimeKind.Local).AddTicks(1786),
                            Name = "beginner",
                            Note = "CompetencyLevel(beginner)"
                        },
                        new
                        {
                            Id = 2,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 68, DateTimeKind.Local).AddTicks(1812),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 68, DateTimeKind.Local).AddTicks(1812),
                            Name = "elementary",
                            Note = "CompetencyLevel(elementary)"
                        },
                        new
                        {
                            Id = 3,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 68, DateTimeKind.Local).AddTicks(1816),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 68, DateTimeKind.Local).AddTicks(1817),
                            Name = "pre-intermediate",
                            Note = "CompetencyLevel(pre-intermediate)"
                        },
                        new
                        {
                            Id = 4,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 68, DateTimeKind.Local).AddTicks(1820),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 68, DateTimeKind.Local).AddTicks(1821),
                            Name = "intermediate",
                            Note = "CompetencyLevel(intermediate)"
                        },
                        new
                        {
                            Id = 5,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 68, DateTimeKind.Local).AddTicks(1824),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 68, DateTimeKind.Local).AddTicks(1825),
                            Name = "upper-intermediate",
                            Note = "CompetencyLevel(upper-intermediate)"
                        },
                        new
                        {
                            Id = 6,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 68, DateTimeKind.Local).AddTicks(1831),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 68, DateTimeKind.Local).AddTicks(1831),
                            Name = "advanced",
                            Note = "CompetencyLevel(advanced)"
                        },
                        new
                        {
                            Id = 7,
                            CreatedByName = "InitialCreate",
                            CreatedDate = new DateTime(2024, 12, 24, 11, 1, 26, 68, DateTimeKind.Local).AddTicks(1834),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedDate = new DateTime(2024, 12, 24, 11, 1, 26, 68, DateTimeKind.Local).AddTicks(1835),
                            Name = "expert-proficency",
                            Note = "CompetencyLevel(expert-proficency)"
                        });
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CvId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CvId");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.Cv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HeaderImage")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFreelance")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Cvs", (string)null);
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CvId")
                        .HasColumnType("int");

                    b.Property<string>("DateRange")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SchoolDegree")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CvId");

                    b.ToTable("Educations", (string)null);
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CvId")
                        .HasColumnType("int");

                    b.Property<string>("DateRange")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Firm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CvId");

                    b.ToTable("Experiences", (string)null);
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.MyLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CompetencyLevelId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CvId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CompetencyLevelId");

                    b.HasIndex("CvId");

                    b.ToTable("MyLanguages", (string)null);
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("Portfolios", (string)null);
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.PortfolioSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("SkillId");

                    b.ToTable("PortfolioSkills");
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "111517eb-b2f6-4d91-8839-56f38ffc7b8f",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "75f8de0a-921b-4239-a9d9-c608f3ba7b47",
                            Name = "Editor",
                            NormalizedName = "EDITOR"
                        });
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Services", (string)null);
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CompetencyLevelId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CvId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CompetencyLevelId");

                    b.HasIndex("CvId");

                    b.ToTable("Skills", (string)null);
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.SocialMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CvId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CvId");

                    b.ToTable("SocialMedias", (string)null);
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("About")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FacebookLink")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("GitHubLink")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("InstagramLink")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LinkedInLink")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwitterLink")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WebsiteLink")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("YoutubeLink")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "Admin User About...",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "04c33ccd-faf2-48ce-b441-d033d86864dc",
                            Email = "admin@emreakdemir.net",
                            EmailConfirmed = true,
                            FacebookLink = "https://facebook.com/",
                            FirstName = "Admin",
                            GitHubLink = "https://github.com/",
                            InstagramLink = "https://instagram.com/",
                            LastName = "Admin",
                            LinkedInLink = "https://linkedin.com/",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EMREAKDEMIR.NET",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEEPHM9PJx1C3oPlyTAiM3/OUQ7atMe8odQcuvC7We1nfvi9mY+GbwLkybKei028IBA==",
                            PhoneNumber = "5551112233",
                            PhoneNumberConfirmed = true,
                            Picture = "defaultUser.png",
                            SecurityStamp = "466f9983-e2b7-4177-95b6-e10b77496286",
                            TwitterLink = "https://twitter.com/",
                            TwoFactorEnabled = false,
                            UserName = "admin",
                            WebsiteLink = "https://emreakdemir.net.com/",
                            YoutubeLink = "https://youtube.com/"
                        },
                        new
                        {
                            Id = 2,
                            About = "Editor User About...",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6663cab0-dcab-42e0-ae16-c31caff7f1e6",
                            Email = "editor@emreakdemir.net",
                            EmailConfirmed = true,
                            FacebookLink = "https://facebook.com/",
                            FirstName = "Editor",
                            GitHubLink = "https://github.com/",
                            InstagramLink = "https://instagram.com/",
                            LastName = "Editor",
                            LinkedInLink = "https://linkedin.com/",
                            LockoutEnabled = false,
                            NormalizedEmail = "EDITOR@EMREAKDEMIR.NET",
                            NormalizedUserName = "EDITOR",
                            PasswordHash = "AQAAAAIAAYagAAAAEJfKPz3+lTmbFwjfY9OyTYqi0MgEJYE7EEXdyhXMSjP6Y880t/SFsk5E0Dl1/5m7MA==",
                            PhoneNumber = "5551112234",
                            PhoneNumberConfirmed = true,
                            Picture = "defaultUser.png",
                            SecurityStamp = "d9122a3a-6c92-45ad-ae43-c48eb37001ad",
                            TwitterLink = "https://twitter.com/",
                            TwoFactorEnabled = false,
                            UserName = "editor",
                            WebsiteLink = "https://emreakdemir.net.com/",
                            YoutubeLink = "https://youtube.com/"
                        });
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.UserToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.Article", b =>
                {
                    b.HasOne("CvBlog.Entities.Concrete.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CvBlog.Entities.Concrete.User", "User")
                        .WithMany("Articles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.Comment", b =>
                {
                    b.HasOne("CvBlog.Entities.Concrete.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.Customer", b =>
                {
                    b.HasOne("CvBlog.Entities.Concrete.Cv", null)
                        .WithMany("Customers")
                        .HasForeignKey("CvId");
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.Education", b =>
                {
                    b.HasOne("CvBlog.Entities.Concrete.Cv", null)
                        .WithMany("Educations")
                        .HasForeignKey("CvId");
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.Experience", b =>
                {
                    b.HasOne("CvBlog.Entities.Concrete.Cv", null)
                        .WithMany("Experiences")
                        .HasForeignKey("CvId");
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.MyLanguage", b =>
                {
                    b.HasOne("CvBlog.Entities.Concrete.CompetencyLevel", "CompetencyLevel")
                        .WithMany()
                        .HasForeignKey("CompetencyLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CvBlog.Entities.Concrete.Cv", null)
                        .WithMany("MyLanguages")
                        .HasForeignKey("CvId");

                    b.Navigation("CompetencyLevel");
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.Portfolio", b =>
                {
                    b.HasOne("CvBlog.Entities.Concrete.Service", "Service")
                        .WithMany("Portfolios")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.PortfolioSkill", b =>
                {
                    b.HasOne("CvBlog.Entities.Concrete.Portfolio", "Portfolio")
                        .WithMany("PortfolioSkills")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CvBlog.Entities.Concrete.Skill", "Skill")
                        .WithMany("SkillPortfolios")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.RoleClaim", b =>
                {
                    b.HasOne("CvBlog.Entities.Concrete.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.Skill", b =>
                {
                    b.HasOne("CvBlog.Entities.Concrete.CompetencyLevel", "CompetencyLevel")
                        .WithMany()
                        .HasForeignKey("CompetencyLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CvBlog.Entities.Concrete.Cv", null)
                        .WithMany("Skills")
                        .HasForeignKey("CvId");

                    b.Navigation("CompetencyLevel");
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.SocialMedia", b =>
                {
                    b.HasOne("CvBlog.Entities.Concrete.Cv", null)
                        .WithMany("SocialMedias")
                        .HasForeignKey("CvId");
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.UserClaim", b =>
                {
                    b.HasOne("CvBlog.Entities.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.UserLogin", b =>
                {
                    b.HasOne("CvBlog.Entities.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.UserRole", b =>
                {
                    b.HasOne("CvBlog.Entities.Concrete.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CvBlog.Entities.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.UserToken", b =>
                {
                    b.HasOne("CvBlog.Entities.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.Article", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.Category", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.Cv", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Educations");

                    b.Navigation("Experiences");

                    b.Navigation("MyLanguages");

                    b.Navigation("Skills");

                    b.Navigation("SocialMedias");
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.Portfolio", b =>
                {
                    b.Navigation("PortfolioSkills");
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.Service", b =>
                {
                    b.Navigation("Portfolios");
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.Skill", b =>
                {
                    b.Navigation("SkillPortfolios");
                });

            modelBuilder.Entity("CvBlog.Entities.Concrete.User", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
